version: '3.4'

services:
  ontop:
    image: ontop/ontop
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ontology-complete.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/ontology-complete.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ontology.docker.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    ports:
      - "8080:8080"